export const data = [
	{
		id: 1,
		img: 'https://i.imgur.com/rMXzShv.jpg',
		nameProduct: 'Camiseta Blanca con Girasoles',
		price: 75000,
		quantity: 1,
	},
	{
		id: 2,
		img: 'https://i.imgur.com/KDNH4xF.jpg',
		nameProduct: 'Camiseta Vespa Pin Up Negra',
		price: 70000,
		quantity: 1,
	},
	{
		id: 3,
		img: 'https://i.imgur.com/gRdAoQe.jpg',
		nameProduct: 'Camiseta Vespa Pin Up Verde',
		price: 60000,
		quantity: 1,
	},
	{
		id: 4,
		img: 'https://i.imgur.com/rLjq9bm.jpg',
		nameProduct: 'Vestido Girasoles',
		price: 100000,
		quantity: 1,
	},
	{
		id: 5,
		img: 'https://i.imgur.com/Ebu7pCf.jpg',
		nameProduct: 'Camiseta Girasoles Amarilla',
		price: 65000,
		quantity: 1,
	},
  {
		id: 6,
		img: 'https://i.imgur.com/Z6wHDAD.jpg',
		nameProduct: 'Camiseta Gato',
		price: 60000,
		quantity: 1,
	},
  {
		id: 7,
		img: 'https://i.imgur.com/GZX7Dtj.jpg',
		nameProduct: 'Camiseta Orquideas y Colibrí',
		price: 75000,
		quantity: 1,
	},
  {
		id: 8,
		img: 'https://i.imgur.com/zNL0Eyf.jpg',
		nameProduct: 'Camiseta Ranas Venenosas',
		price: 80000,
		quantity: 1,
	},
  {
		id: 9,
		img: 'https://i.imgur.com/V001zdi.jpg',
		nameProduct: 'Camiseta Leopardo',
		price: 75000,
		quantity: 1,
	},
  {
		id: 10,
		img: 'https://i.imgur.com/a2A5eWg.jpg',
		nameProduct: 'Camiseta Película IT',
		price: 85000,
		quantity: 1,
	},
	
];